### ISSUE TITLE
Unable to use arguments when starting capybara

### ISSUE THREAD

**Issue by sadgrlonline** [fuwn/capybara#1]
Hello! I am using this great tool to host a gemini proxy. I can't figure out how to get the arguments to work (specifically -e style.css for the stylesheet). It doesn't seem to recognize any of those commands. 

For example if I type: `./capybara gemini://cities.yesterweb.org/ -e https://yesterweb.org/css/gemini.css` (or use any arguments) I get the following output:

`./capybara <gemini root>`

I built from this github source with Go, I did not use Docker and I'm on Ubuntu if that helps. Let me know if you need any more information.

**Comment by Fuwn** [comment]
The flag arguments are only picked up if they are entered before the Gemini root: `./capybara [args] <gemini root>`.

Valid: `./capybara -e https://yesterweb.org/css/gemini.css gemini://cities.yesterweb.org/`
Invalid: `./capybara gemini://cities.yesterweb.org/ -e https://yesterweb.org/css/gemini.css`

This behaviour and "error output" have been persistent since pre-fork. If I have some time I'll see if there's anything I can do to optionally flag argument-ize the Gemini root argument enabling mixed argument passing.
